com:
  alipay:
    sofa:
      rpc:
        registry-address: nacos://172.16.31.210:31256/dev
        bolt-port: 20002


spring:
  application:
    name: user
  profiles:
    active: dev

server:
  port: 8080
